/* ============================================================
   chapter1.js, Chương 1: Tấm Cám (trọn truyện, 14 màn)
   Thêm chương mới: tạo file chapters/chapterN.js cùng cấu trúc,
   push vào CHAPTERS rồi khai <script> trong index.html.
   ============================================================ */
window.CHAPTERS = window.CHAPTERS || [];

CHAPTERS.push({
  id: 1,
  name: "Chương 1 · Tấm Cám",
  levels: [

  /* ---- Phần 1: Tấm ở nhà dì ghẻ ---- */
  {type:"place", name:"Bắt tép", cols:4, rows:3,
   scene:"@c1.battep.scene",
   env:[{id:"ao",cells:[[0,0],[0,1]]},{id:"tre",cells:[[3,0]]},{id:"cayda",cells:[[3,2]]}], blocked:[], mud:[],
   chars:["tam"],
   cons:[{t:"adjEnv",c:"tam",e:"ao",txt:"Tấm đứng cạnh ao"}],
   story:"@c1.battep.story"},

  {type:"place", name:"Giỏ tép", cols:4, rows:3,
   scene:"@c1.giotep.scene",
   env:[{id:"ao",cells:[[0,0]]},{id:"nui",cells:[[3,0]]},{id:"tre",cells:[[3,2]]}], blocked:[[2,0]], mud:[],
   relic:{id:"yemdo",cell:[2,2]},
   chars:["tam","cam"],
   cons:[{t:"adjEnv",c:"tam",e:"ao",txt:"Tấm đứng cạnh ao"},
         {t:"behind",c:"cam",target:"tam",txt:"Cám đứng sau lưng Tấm"}],
   story:"@c1.giotep.story"},

  {type:"place", name:"Bụt hiện lên", cols:4, rows:3,
   scene:"@c1.buthienlen.scene",
   env:[{id:"gieng",cells:[[1,1]]},{id:"cayda",cells:[[3,0]]},{id:"tre",cells:[[3,2]]}], blocked:[[0,2]], mud:[],
   chars:["tam","but","bong"],
   cons:[{t:"adjEnv",c:"tam",e:"gieng",txt:"Tấm ngồi khóc bên giếng"},
         {t:"adjChar",c:"but",target:"tam",txt:"Bụt hiện lên bên người đang khóc"},
         {t:"onEnv",c:"bong",e:"gieng",txt:"Thả Bống xuống giếng"}],
   story:"@c1.buthienlen.story"},

  {type:"matrix", name:"Sáng hôm sau",
   scene:"@c1.sanghomsau.scene",
   rows:["tam","cam","dighe"], colsM:["dong","san","boao"],
   clues:[{t:"mIs", c:"cam", col:"san",  txt:"Cám sợ nắng, chỉ quanh quẩn trong sân nhà"},
          {t:"mNot",c:"dighe",col:"dong",txt:"Dì ghẻ không bao giờ bước chân vào bùn lầy"},
          {t:"mUniq",txt:"Mỗi nơi chỉ có một người"}],
   story:"@c1.sanghomsau.story"},

  {type:"place", name:"Nuôi Bống", cols:4, rows:4,
   scene:"@c1.nuoibong.scene",
   env:[{id:"gieng",cells:[[1,1]]},{id:"cayda",cells:[[3,3]]},{id:"caythi",cells:[[0,0]]},{id:"tre",cells:[[3,0]]},{id:"nha",cells:[[0,3]]}], blocked:[[3,1]], mud:[],
   chars:["tam","cam","dighe"],
   cons:[{t:"adjEnv",c:"tam",e:"gieng",txt:"Tấm đứng cạnh giếng"},
         {t:"behind",c:"cam",target:"tam",txt:"Cám đứng sau lưng Tấm"},
         {t:"adjEnv",c:"dighe",e:"nha",txt:"Dì ghẻ ngồi trong nhà, ngại ra sân bẩn chân"}],
   story:"@c1.nuoibong.story"},

  {type:"place", name:"Nghe lén", cols:4, rows:3,
   scene:"@c1.nghelen.scene",
   env:[{id:"gieng",cells:[[1,1]]},{id:"tre",cells:[[2,0]]},{id:"nui",cells:[[0,0]]}], blocked:[], mud:[],
   walls:[[1,2,"r"]],
   chars:["tam","cam"],
   occupy:[{c:"cam",e:"tre",mode:"hide"}],
   cons:[{t:"adjEnv",c:"tam",e:"gieng",txt:"Tấm đứng bên giếng gọi Bống"},
         {t:"listen",c:"cam",target:"tam",txt:"Cám nghe lén, kề bên nhưng không bị thấy!"}],
   story:"@c1.nghelen.story"},

  {type:"place", name:"Chăn trâu đồng xa", cols:5, rows:4,
   scene:"@c1.chantraudongxa.scene",
   env:[{id:"gieng",cells:[[0,1]]},{id:"baico",cells:[[4,2]]},{id:"tre",cells:[[2,0]]},{id:"nui",cells:[[2,2]]}], blocked:[], mud:[],
   chars:["tam","trau","dighe","cam"],
   cons:[{t:"adjEnv",c:"trau",e:"baico",txt:"Trâu gặm cỏ ở đồng xa"},
         {t:"adjChar",c:"tam",target:"trau",txt:"Tấm đi theo giữ trâu"},
         {t:"adjEnv",c:"dighe",e:"gieng",txt:"Dì ghẻ đứng bên giếng giả giọng gọi"},
         {t:"behind",c:"cam",target:"dighe",txt:"Cám cầm giỏ nấp sau lưng mẹ"}],
   story:"@c1.chantraudongxa.story"},

  {type:"place", name:"Nhặt thóc", cols:5, rows:4,
   scene:"@c1.nhatthoc.scene",
   env:[{id:"thung",cells:[[3,0]]},{id:"cong",cells:[[0,2]]},{id:"dinh",cells:[[4,3]]},{id:"nha",cells:[[2,0]]},{id:"cayda",cells:[[4,0]]},{id:"tre",cells:[[0,0]]}], blocked:[[2,2]], mud:[[0,1],[1,2],[1,3]],
   chars:["tam","chim","cam","dighe"],
   cons:[{t:"adjEnv",c:"tam",e:"thung",txt:"Tấm ngồi cạnh thúng thóc"},
         {t:"behind",c:"chim",target:"tam",txt:"Chim sẻ sà xuống sau lưng Tấm"},
         {t:"adjEnv",c:"cam",e:"cong",txt:"Cám ra cổng làng đi hội"},
         {t:"queue",cs:["cam","dighe"],txt:"Dì ghẻ theo sát Cám"},
         {t:"notTer",c:"dighe",txt:"Dì ghẻ tránh vũng bùn"}],
   story:"@c1.nhatthoc.story"},

  {type:"matrix", name:"Đêm hội",
   scene:"@c1.demhoi.scene",
   rows:["cam","dighe","balao"], colsM:["sandinh","baico","duongbun"],
   clues:[{t:"mIs", c:"balao",col:"sandinh", txt:"Bà lão dọn hàng nước nơi đông người nhất, sân đình"},
          {t:"mNot",c:"dighe",col:"duongbun",txt:"Dì ghẻ chẳng đời nào dẫm vào bùn"},
          {t:"mNot",c:"cam",  col:"baico",   txt:"Cám chê bãi cỏ tối om, chẳng thấy hội đâu"},
          {t:"mUniq",txt:"Mỗi nơi chỉ có một người"}],
   story:"@c1.demhoi.story"},

  /* ---- Phần 2: Gặp vua ---- */
  {type:"place", name:"Thử hài", cols:5, rows:4,
   scene:"@c1.thuhai.scene",
   env:[{id:"kieu",cells:[[1,1],[2,1]]},{id:"dinh",cells:[[4,0]]},{id:"tre",cells:[[0,2]]},{id:"cayda",cells:[[4,3]]}], blocked:[[0,1]], mud:[[1,2],[2,2]],
   extras:[{c:"bom",cell:[4,3],note:"cậu bé chăn trâu nào đó lẻn vào xem hội…"}],
   chars:["tam","vua","cam","dighe","balao"],
   cons:[{t:"adjEnv",c:"vua",e:"kieu",txt:"Vua ngự cạnh kiệu"},
         {t:"adjEnv",c:"tam",e:"kieu",txt:"Tấm đứng cạnh kiệu"},
         {t:"adjChar",c:"tam",target:"vua",txt:"Tấm đến trước mặt vua thử hài"},
         {t:"adjEnv",c:"dighe",e:"kieu",txt:"Dì ghẻ đứng cạnh kiệu"},
         {t:"adjChar",c:"dighe",target:"cam",txt:"Dì ghẻ đi kèm Cám"},
         {t:"adjEnv",c:"cam",e:"dinh",txt:"Cám chen lên phía sân đình cho gần kiệu"},
         {t:"adjEnv",c:"balao",e:"tre",txt:"Bà lão đứng nép bên bụi tre, ôm bị trầu"},
         {t:"notTer",c:"vua",txt:"Vua không để long bào dính bùn"}],
   story:"@c1.thuhai.story"},

  {type:"place", name:"Về cung", cols:4, rows:3,
   scene:"@c1.vecung.scene",
   env:[{id:"cung",cells:[[0,0]]},{id:"nui",cells:[[3,0]]},{id:"tre",cells:[[3,2]]}], blocked:[], mud:[],
   chars:["vua","tam","linh"],
   cons:[{t:"adjEnv",c:"vua",e:"cung",txt:"Vua đứng bên hiên cung"},
         {t:"adjChar",c:"tam",target:"vua",txt:"Tấm ở bên vua"},
         {t:"adjChar",c:"linh",target:"vua",txt:"Lính hộ giá cạnh vua"}],
   story:"@c1.vecung.story"},

  /* ---- Phần 3: Hoá thân ---- */
  {type:"place", name:"Cây cau", cols:4, rows:3,
   scene:"@c1.caycau.scene",
   env:[{id:"caycau",cells:[[1,0]]},{id:"tre",cells:[[0,2]]},{id:"gieng",cells:[[3,2]]}], blocked:[], mud:[],
   walls:[[0,0,"r"],[1,0,"b"]],
   chars:["tam","dighe","cam"],
   cons:[{t:"onEnv",c:"tam",e:"caycau",txt:"Tấm trèo lên cây cau"},
         {t:"adjEnv",c:"dighe",e:"caycau",txt:"Dì ghẻ đứng ngay gốc cau (rào chắn thì không tính!)"},
         {t:"hideIn",c:"cam",e:"tre",txt:"Cám nấp trong bụi tre"}],
   story:"@c1.caycau.story"},

  {type:"place", name:"Chim vàng anh", cols:4, rows:3,
   scene:"@c1.chimvanganh.scene",
   env:[{id:"cung",cells:[[3,0]]},{id:"saophoi",cells:[[1,2]]},{id:"tre",cells:[[0,0]]}], blocked:[], mud:[],
   chars:["vua","vanganh","cam"],
   cons:[{t:"adjEnv",c:"vua",e:"cung",txt:"Vua đứng bên hiên cung"},
         {t:"adjChar",c:"vanganh",target:"vua",txt:"Vàng anh đậu bên vua, mắng vọng sang"},
         {t:"adjEnv",c:"cam",e:"saophoi",txt:"Cám phơi áo bên sào"},
         {t:"notAdjChar",c:"cam",target:"vanganh",txt:"Cám né vàng anh, không dám lại gần"}],
   story:"@c1.chimvanganh.story"},

  {type:"matrix", name:"Vua đi tìm",
   scene:"@c1.vuaditim.scene",
   rows:["vua","cam","dighe"], colsM:["xoandao","khungcui","sanphoi"],
   clues:[{t:"mIs", c:"vua", col:"xoandao", txt:"Vua nhớ vàng anh, ngồi cả ngày dưới bóng xoan đào"},
          {t:"mNot",c:"cam", col:"khungcui",txt:"Cám nghe khung cửi kêu “kẽo cà kẽo kẹt” mà sởn gai ốc, không dám lại gần"},
          {t:"mUniq",txt:"Mỗi nơi chỉ có một người"}],
   story:"@c1.vuaditim.story"},

  {type:"place", name:"Quả thị", cols:4, rows:3,
   scene:"@c1.quathi.scene",
   env:[{id:"caythi",cells:[[3,0]]},{id:"quan",cells:[[3,2]]},{id:"gieng",cells:[[0,0]]}], blocked:[], mud:[],
   chars:["balao","qthi"],
   cons:[{t:"adjEnv",c:"balao",e:"caythi",txt:"Bà lão ngồi cạnh cây thị"},
         {t:"adjEnv",c:"balao",e:"quan",txt:"Bà lão ngồi cạnh quán nước"},
         {t:"adjChar",c:"qthi",target:"balao",txt:"Quả thị rơi cạnh bà lão"}],
   story:"@c1.quathi.story"},

  /* ---- Điểm xuyết: kể lại chuỗi hoá thân ---- */
  {type:"story", name:"Bốn kiếp của Tấm",
   scene:"@c1.bonkiepcuatam.scene",
   pieces:["khungcui","qthi","vanganh","xoandao"],
   panels:[
     {label:"@c1.bonkiepcuatam.p1.label", who:["vua","cam"],
      cue:"@c1.bonkiepcuatam.p1.cue",
      answer:"vanganh", after:"@c1.bonkiepcuatam.p1.after"},
     {label:"@c1.bonkiepcuatam.p2.label", who:["vua"],
      cue:"@c1.bonkiepcuatam.p2.cue",
      answer:"xoandao", after:"@c1.bonkiepcuatam.p2.after"},
     {label:"@c1.bonkiepcuatam.p3.label", who:["dighe"],
      cue:"@c1.bonkiepcuatam.p3.cue",
      answer:"khungcui", after:"@c1.bonkiepcuatam.p3.after"},
     {label:"@c1.bonkiepcuatam.p4.label", who:["balao"],
      cue:"@c1.bonkiepcuatam.p4.cue",
      answer:"qthi", after:"@c1.bonkiepcuatam.p4.after"}
   ],
   revealArt:"tam", reveal:"@c1.bonkiepcuatam.reveal",
   story:"@c1.bonkiepcuatam.story"},

  /* ---- Phần 4: Đoàn tụ ---- */
  {type:"place", name:"Miếng trầu", cols:4, rows:3,
   scene:"@c1.miengtrau.scene",
   env:[{id:"caythi",cells:[[3,0]]},{id:"quan",cells:[[3,2]]}], blocked:[], mud:[],
   chars:["vua","linh","balao","tam"],
   cons:[{t:"adjEnv",c:"vua",e:"quan",txt:"Vua ghé bên quán nước"},
         {t:"adjEnv",c:"balao",e:"quan",txt:"Bà lão ngồi bên quán"},
         {t:"adjChar",c:"tam",target:"balao",txt:"Tấm ở cạnh bà lão"},
         {t:"adjChar",c:"linh",target:"vua",txt:"Lính hộ giá cạnh vua"}],
   story:"@c1.miengtrau.story"},

  {type:"place", name:"Đón Tấm về cung", cols:5, rows:4,
   scene:"@c1.dontamvecung.scene",
   env:[{id:"kieu",cells:[[2,1]]},{id:"cung",cells:[[4,0]]},{id:"caycau",cells:[[0,0]]},{id:"mocau",cells:[[0,1]]},{id:"nui",cells:[[0,3]]},{id:"tre",cells:[[4,3]]},{id:"cayda",cells:[[2,3]]},{id:"tangda",cells:[[4,2]]},{id:"baico",cells:[[1,3]]},{id:"caythi",cells:[[2,0]]}], blocked:[], mud:[],
   chars:["tam","vua","linh","balao"],
   cons:[{t:"onEnv",c:"tam",e:"kieu",txt:"Tấm ngồi lên kiệu hoa"},
         {t:"adjChar",c:"vua",target:"tam",txt:"Vua đi bên kiệu"},
         {t:"adjEnv",c:"linh",e:"cung",txt:"Lính dẹp đường trước cửa cung"},
         {t:"adjEnv",c:"balao",e:"mocau",txt:"Bà lão đứng bên chiếc mo cau năm xưa"}],
   story:"@c1.dontamvecung.story"},

]});
