/* ============================================================
   chapter1.js — Chương 1: Tấm Cám (trọn truyện, 14 màn)
   Thêm chương mới: tạo file chapters/chapterN.js cùng cấu trúc,
   push vào CHAPTERS rồi khai <script> trong index.html.
   ============================================================ */
window.CHAPTERS = window.CHAPTERS || [];

CHAPTERS.push({
  id: 1,
  name: "Chương 1 · Tấm Cám",
  levels: [

  /* ---- Phần 1: Tấm ở nhà dì ghẻ ---- */
  {type:"place", name:"Bắt tép", cols:4, rows:3,
   scene:"Ngày ngày, Tấm ra đồng mò cua bắt tép. <b>Chạm vào Tấm, rồi chạm vào ô đất cạnh ao.</b>",
   env:[{id:"ao",cells:[[0,0],[0,1]]},{id:"tre",cells:[[3,0]]},{id:"cayda",cells:[[3,2]]}], blocked:[], mud:[],
   chars:["tam"],
   cons:[{t:"adjEnv",c:"tam",e:"ao",txt:"Tấm đứng cạnh ao"}],
   story:"Chẳng mấy chốc, giỏ của Tấm đã đầy tép!"},

  {type:"place", name:"Giỏ tép", cols:4, rows:3,
   scene:"Cám cũng ra đồng… nhưng chỉ lén đứng <b>sau lưng</b> Tấm. Tấm nhìn về phía ao — ô sau lưng có viền xanh chấm chấm.",
   env:[{id:"ao",cells:[[0,0]]},{id:"nui",cells:[[3,0]]},{id:"tre",cells:[[3,2]]}], blocked:[[2,0]], mud:[],
   chars:["tam","cam"],
   cons:[{t:"adjEnv",c:"tam",e:"ao",txt:"Tấm đứng cạnh ao"},
         {t:"behind",c:"cam",target:"tam",txt:"Cám đứng sau lưng Tấm"}],
   story:"“Chị Tấm ơi, đầu chị lấm!” — thừa lúc Tấm gội đầu, Cám trút hết giỏ tép mang về…"},

  {type:"place", name:"Bụt hiện lên", cols:4, rows:3,
   scene:"Mất giỏ tép, Tấm ôm mặt khóc bên giếng. Bỗng có làn khói thơm — <b>Bụt</b> hiện lên: “Vì sao con khóc?” Bụt cho Tấm một con <b>cá bống</b>, dặn thả xuống giếng mà nuôi.",
   env:[{id:"gieng",cells:[[1,1]]},{id:"cayda",cells:[[3,0]]},{id:"tre",cells:[[3,2]]}], blocked:[[0,2]], mud:[],
   chars:["tam","but","bong"],
   cons:[{t:"adjEnv",c:"tam",e:"gieng",txt:"Tấm ngồi khóc bên giếng"},
         {t:"adjChar",c:"but",target:"tam",txt:"Bụt hiện lên bên người đang khóc"},
         {t:"onEnv",c:"bong",e:"gieng",txt:"Thả Bống xuống giếng"}],
   story:"“<i>Bống bống bang bang…</i>” — từ nay, ngày nào Tấm cũng có Bống làm bạn."},

  {type:"matrix", name:"Sáng hôm sau",
   scene:"Sáng hôm sau, ba người mỗi người một nơi — <b>mỗi nơi chỉ một người</b>. Đọc manh mối rồi chạm vào ô để đánh dấu ai ở đâu. Để ý: ngoài đồng toàn <b>bùn lầy</b>!",
   rows:["tam","cam","dighe"], colsM:["dong","san","boao"],
   clues:[{t:"mIs", c:"cam", col:"san",  txt:"Cám sợ nắng, chỉ quanh quẩn trong sân nhà"},
          {t:"mNot",c:"dighe",col:"dong",txt:"Dì ghẻ không bao giờ bước chân vào bùn lầy"},
          {t:"mUniq",txt:"Mỗi nơi chỉ có một người"}],
   story:"Tấm lội ruộng từ sớm, Cám đủng đỉnh trong sân… còn dì ghẻ ngồi bờ ao, chăm chăm nhìn xuống nước — dưới đó có một con cá lạ."},

  {type:"place", name:"Nuôi Bống", cols:4, rows:4,
   scene:"Tấm nuôi cá Bống dưới giếng, ngày ngày gọi: <i>“Bống bống bang bang…”</i> Cám lại rình sau lưng. Còn dì ghẻ thì <b>không được</b> đứng cạnh giếng!",
   env:[{id:"gieng",cells:[[1,1]]},{id:"cayda",cells:[[3,3]]}], blocked:[[3,1]], mud:[],
   chars:["tam","cam","dighe"],
   cons:[{t:"adjEnv",c:"tam",e:"gieng",txt:"Tấm đứng cạnh giếng"},
         {t:"behind",c:"cam",target:"tam",txt:"Cám đứng sau lưng Tấm"},
         {t:"notAdjEnv",c:"dighe",e:"gieng",txt:"Dì ghẻ KHÔNG cạnh giếng"}],
   story:"Bống ngoi lên, ăn cơm vàng cơm bạc của Tấm. Nhưng một hôm, dì ghẻ giả giọng gọi và bắt mất Bống… Tấm khóc, Bụt lại hiện lên: “Con tìm xương bống, bỏ vào bốn cái hũ, chôn dưới chân giường.”"},

  {type:"place", name:"Nhặt thóc", cols:5, rows:4,
   scene:"Dì ghẻ trộn thóc lẫn gạo, bắt Tấm nhặt xong mới được đi hội. May sao Bụt sai <b>đàn chim sẻ</b> đến giúp. Mẹ con Cám rủ nhau ra cổng làng — nhưng đường vừa mưa, có mấy <b>vũng bùn</b>, mà dì ghẻ thì chúa ghét bẩn chân…",
   env:[{id:"thung",cells:[[3,0]]},{id:"cong",cells:[[0,2]]},{id:"dinh",cells:[[4,3]]}], blocked:[[2,2]], mud:[[0,1],[1,2]],
   chars:["tam","chim","cam","dighe"],
   cons:[{t:"adjEnv",c:"tam",e:"thung",txt:"Tấm ngồi cạnh thúng thóc"},
         {t:"adjChar",c:"chim",target:"tam",txt:"Chim sẻ đậu cạnh Tấm"},
         {t:"adjEnv",c:"cam",e:"cong",txt:"Cám đứng cạnh cổng làng"},
         {t:"adjChar",c:"dighe",target:"cam",txt:"Dì ghẻ đi kèm Cám"},
         {t:"notTer",c:"dighe",txt:"Dì ghẻ không dẫm vào bùn"}],
   story:"Đàn chim sẻ sà xuống nhặt giúp Tấm! Rồi từ bốn chiếc hũ dưới chân giường, Tấm có áo đẹp và một <b>đôi hài thêu</b> để đi hội. Mẹ con Cám lách qua vũng bùn, đi trước mất rồi."},

  {type:"matrix", name:"Đêm hội",
   scene:"Đêm hội làng! Cám, dì ghẻ và bà lão bán nước mỗi người một chỗ — <b>mỗi nơi một người</b>. Đường làng đêm qua mưa, toàn <b>bùn lầy</b>.",
   rows:["cam","dighe","balao"], colsM:["sandinh","baico","duongbun"],
   clues:[{t:"mIs", c:"balao",col:"sandinh", txt:"Bà lão dọn hàng nước nơi đông người nhất — sân đình"},
          {t:"mNot",c:"dighe",col:"duongbun",txt:"Dì ghẻ chẳng đời nào dẫm vào bùn"},
          {t:"mNot",c:"cam",  col:"baico",   txt:"Cám chê bãi cỏ tối om, chẳng thấy hội đâu"},
          {t:"mUniq",txt:"Mỗi nơi chỉ có một người"}],
   story:"Hội làng tưng bừng. Nghe nói bên vũng bùn đường làng, có người đánh rơi một chiếc hài thêu…"},

  /* ---- Phần 2: Gặp vua ---- */
  {type:"place", name:"Thử hài", cols:5, rows:4,
   scene:"<b>Nhà vua</b> mở hội thử hài! Vua ngự bên kiệu, ai cũng chen đến gần. Dì ghẻ phải kèm Cám, Tấm thì tránh xa dì ghẻ — sân đình sau mưa còn mấy vũng bùn, mà long bào của vua thì không được bẩn…",
   env:[{id:"kieu",cells:[[1,1],[2,1]]},{id:"dinh",cells:[[4,0]]},{id:"tre",cells:[[0,2]]}], blocked:[[0,1]], mud:[[1,3],[3,3]],
   chars:["tam","vua","cam","dighe","balao"],
   cons:[{t:"adjEnv",c:"vua",e:"kieu",txt:"Vua ngự cạnh kiệu"},
         {t:"adjEnv",c:"tam",e:"kieu",txt:"Tấm đứng cạnh kiệu"},
         {t:"adjChar",c:"tam",target:"vua",txt:"Tấm đến trước mặt vua thử hài"},
         {t:"adjEnv",c:"cam",e:"kieu",txt:"Cám đứng cạnh kiệu"},
         {t:"adjEnv",c:"dighe",e:"kieu",txt:"Dì ghẻ đứng cạnh kiệu"},
         {t:"adjEnv",c:"balao",e:"kieu",txt:"Bà lão đứng cạnh kiệu"},
         {t:"adjChar",c:"dighe",target:"cam",txt:"Dì ghẻ đi kèm Cám"},
         {t:"notAdjChar",c:"tam",target:"dighe",txt:"Tấm KHÔNG cạnh dì ghẻ"},
         {t:"notTer",c:"vua",txt:"Vua không để long bào dính bùn"}],
   story:"Chiếc hài vừa như in! Vua nắm tay Tấm, rước nàng lên kiệu về cung."},

  {type:"place", name:"Về cung", cols:4, rows:3,
   scene:"Trong cung, ngày ngày Tấm ở bên vua, có lính canh hộ giá. Nhưng sắp đến ngày giỗ cha, Tấm xin phép về nhà…",
   env:[{id:"cung",cells:[[0,0]]},{id:"nui",cells:[[3,0]]},{id:"tre",cells:[[3,2]]}], blocked:[], mud:[],
   chars:["vua","tam","linh"],
   cons:[{t:"adjEnv",c:"vua",e:"cung",txt:"Vua đứng bên hiên cung"},
         {t:"adjChar",c:"tam",target:"vua",txt:"Tấm ở bên vua"},
         {t:"adjChar",c:"linh",target:"vua",txt:"Lính hộ giá cạnh vua"}],
   story:"Vua dặn: “Nàng về giỗ cha, rồi sớm quay lại nhé.” Tấm hứa, rồi theo đường làng về nhà dì ghẻ…"},

  /* ---- Phần 3: Hoá thân ---- */
  {type:"place", name:"Cây cau", cols:4, rows:3,
   scene:"Về nhà, dì ghẻ ngọt nhạt: “Con <b>trèo lên cây cau</b> hái buồng cau cúng cha.” Quanh gốc cau có <b>hàng rào</b> — đứng ngoài rào thì không với tới gốc đâu. Còn Cám thì <b>nấp trong bụi tre</b> đầu ngõ canh chừng…",
   env:[{id:"caycau",cells:[[1,0]]},{id:"tre",cells:[[0,2]]},{id:"gieng",cells:[[3,2]]}], blocked:[], mud:[],
   walls:[[0,0,"r"],[1,0,"b"]],
   chars:["tam","dighe","cam"],
   cons:[{t:"onEnv",c:"tam",e:"caycau",txt:"Tấm trèo lên cây cau"},
         {t:"adjEnv",c:"dighe",e:"caycau",txt:"Dì ghẻ đứng ngay gốc cau (rào chắn thì không tính!)"},
         {t:"hideIn",c:"cam",e:"tre",txt:"Cám nấp trong bụi tre"}],
   story:"Rắc! Dì ghẻ chặt cây, cau đổ… Nhưng từ tán lá, một con <b>chim vàng anh</b> vụt bay về phía cung vua. Chỉ còn chiếc <b>mo cau</b> rơi lại bên vệ đường…"},

  {type:"place", name:"Chim vàng anh", cols:4, rows:3,
   scene:"Chim vàng anh bay vào vườn ngự, quấn quýt bên vua. Cám — nay được dì đưa vào cung thế chỗ — lại lén rình <b>sau lưng vua</b>…",
   env:[{id:"cung",cells:[[3,0]]},{id:"cayda",cells:[[0,0]]},{id:"tre",cells:[[0,2]]}], blocked:[], mud:[],
   chars:["vua","vanganh","cam"],
   cons:[{t:"adjEnv",c:"vua",e:"cung",txt:"Vua đứng bên hiên cung"},
         {t:"adjChar",c:"vanganh",target:"vua",txt:"Vàng anh quấn quýt bên vua"},
         {t:"behind",c:"cam",target:"vua",txt:"Cám rình sau lưng vua"}],
   story:"“<i>Vàng ảnh vàng anh, có phải vợ anh, chui vào tay áo!</i>” — chim sà xuống đậu vai vua. Cám tức lắm… Ít hôm sau chim biến mất, nhưng góc vườn lại mọc lên một cây <b>xoan đào</b>."},

  {type:"matrix", name:"Vua đi tìm",
   scene:"Tấm hoá thân hết lần này đến lần khác: xoan đào toả bóng, khung cửi biết kêu… Vua và mẹ con Cám, ai hay lui tới đâu? <b>Mỗi nơi một người.</b>",
   rows:["vua","cam","dighe"], colsM:["xoandao","khungcui","sanphoi"],
   clues:[{t:"mIs", c:"vua", col:"xoandao", txt:"Vua nhớ vàng anh, ngồi cả ngày dưới bóng xoan đào"},
          {t:"mNot",c:"cam", col:"khungcui",txt:"Cám nghe khung cửi kêu “kẽo cà kẽo kẹt” mà sởn gai ốc, không dám lại gần"},
          {t:"mUniq",txt:"Mỗi nơi chỉ có một người"}],
   story:"Đêm đêm khung cửi kêu: “<i>Kẽo cà kẽo kẹt…</i>” Dì ghẻ sợ, đem đốt, rồi đổ tro thật xa. Nào ngờ từ nắm tro, một cây <b>thị</b> xanh mọc lên, ra đúng một quả."},

  {type:"place", name:"Quả thị", cols:4, rows:3,
   scene:"Bên gốc thị có bà lão bán nước. Bà muốn ngồi <b>vừa cạnh cây thị, vừa cạnh quán</b> — và quả thị thơm chỉ rơi vào bị của người ở cạnh…",
   env:[{id:"caythi",cells:[[3,0]]},{id:"quan",cells:[[3,2]]},{id:"gieng",cells:[[0,0]]}], blocked:[], mud:[],
   chars:["balao","qthi"],
   cons:[{t:"adjEnv",c:"balao",e:"caythi",txt:"Bà lão ngồi cạnh cây thị"},
         {t:"adjEnv",c:"balao",e:"quan",txt:"Bà lão ngồi cạnh quán nước"},
         {t:"adjChar",c:"qthi",target:"balao",txt:"Quả thị rơi cạnh bà lão"}],
   story:"Từ quả thị, Tấm bước ra, quét dọn cửa nhà, thổi cơm têm trầu cho bà lão. Hai bà cháu sớm hôm bên nhau."},

  /* ---- Phần 4: Đoàn tụ ---- */
  {type:"place", name:"Miếng trầu", cols:4, rows:3,
   scene:"Một hôm, vua vi hành ngang quán nước, ghé chân xin miếng trầu, lính theo hộ giá. Tấm têm trầu <b>sau lưng bà lão</b>, chưa dám ra mặt…",
   env:[{id:"caythi",cells:[[3,0]]},{id:"quan",cells:[[3,2]]}], blocked:[], mud:[],
   chars:["vua","linh","balao","tam"],
   cons:[{t:"adjEnv",c:"vua",e:"quan",txt:"Vua ghé bên quán nước"},
         {t:"adjEnv",c:"balao",e:"quan",txt:"Bà lão ngồi bên quán"},
         {t:"adjChar",c:"tam",target:"balao",txt:"Tấm ở cạnh bà lão"},
         {t:"adjChar",c:"linh",target:"vua",txt:"Lính hộ giá cạnh vua"}],
   story:"“Trầu này ai têm mà khéo vậy?” — miếng trầu têm <b>cánh phượng</b>, đúng bàn tay Tấm! Bà lão mỉm cười gọi: “Tấm ơi, ra đây con.”"},

  {type:"place", name:"Đón Tấm về cung", cols:5, rows:4,
   scene:"Vua đón Tấm về cung! Kiệu hoa đi qua đầu làng — qua chân núi, qua cả cây cau cũ, nơi chiếc <b>mo cau</b> năm nào vẫn nằm bên đường…",
   env:[{id:"kieu",cells:[[2,1]]},{id:"cung",cells:[[4,0]]},{id:"caycau",cells:[[0,0]]},{id:"mocau",cells:[[0,1]]},{id:"nui",cells:[[0,3]]},{id:"tre",cells:[[4,3]]}], blocked:[], mud:[],
   chars:["tam","vua","linh","balao"],
   cons:[{t:"adjEnv",c:"tam",e:"kieu",txt:"Tấm ngồi bên kiệu hoa"},
         {t:"adjChar",c:"vua",target:"tam",txt:"Vua đi bên Tấm"},
         {t:"adjEnv",c:"linh",e:"kieu",txt:"Lính khiêng kiệu"},
         {t:"adjChar",c:"balao",target:"tam",txt:"Tấm đón cả bà lão theo cùng"}],
   story:"Tấm trở về cung trong tiếng reo của cả làng, đón cả bà lão về phụng dưỡng.<br><b>— Hết chương 1 —</b><br>Còn chiếc mo cau bên đường? Nghe nói một cậu bé chăn trâu tên <b>Bờm</b> đã nhặt lấy, phe phẩy làm quạt…"},

]});
